### ISSUE TITLE
Errors in README.md docker-compose instructions

### ISSUE THREAD

**Issue by epopisces** [jefferyb/docker-shibboleth#2]
The docker-compose sample code in the README.md file is missing a few lines and/or characters, and fails unless modified.

```yaml
services:
  tomcat-server:
    image: tomcat

  shibboleth-sp:
    image: jefferyb/shibboleth
    container_name: shibboleth-sp
```

Should be

```yaml
services:
  tomcat-server:
    image: tomcat
    ports:         # line added
      - 8080:8080  # line added

  shibboleth-sp:
    image: jefferyb/shibboleth-sp  # line modified
    container_name: shibboleth-sp
```
